version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_shadobot
    env_file:
      - ./config/.env
    restart: always  # Reinicia o serviço automaticamente em caso de falhas
    ports:
      - "5433:5432"
    volumes:
      - /media/bismuto/LinuxBackup/DatabasePostgreSQL:/var/lib/postgresql/data  # Persistência de dados no HD de backup

  app:
    build: .
    image: shadobot_image
    container_name: shadobot
    ports:
      - "8000:8000"
    depends_on:
      - db  # Garante que o contêiner "db" (PostgreSQL) esteja rodando antes de iniciar o app
